services:
  - type: web
    name: tryvobackend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: DJANGO_SECRET_KEY
        value: your-secret-key
