services:
  - type: web
    name: yellowspace-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        value: your-secret-key
