services:
  - type: web
    name: tryvobackend
    env: python
    buildCommand: bash backend/build.sh
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: DJANGO_SECRET_KEY
        value: your-secret-key-here
      - key: DJANGO_SUPERUSER_USERNAME
        value: afsal
      - key: DJANGO_SUPERUSER_PASSWORD
        value: afsal
      - key: DJANGO_SUPERUSER_EMAIL
        value: afsal@gmail.com
