services:
  - type: web
    name: tryvobackend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DJANGO_SETTINGS_MODULE
        value: settings
      - key: SECRET_KEY
        value: your-secret-key
